version: "3"

services:
  api-calcequacao:
    container_name: api-calcequacao
    image: api-calcequacao
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./service:/code/service
    networks:
      - backend
    ports:
      - 9000:9000

networks:
  backend:
    driver: bridge